### ISSUE TITLE
Broken stats on Broken site

### ISSUE THREAD

**Issue by filiptronicek** [koj-co/upptime#17]
![image of stats in README](https://user-images.githubusercontent.com/29888641/89780796-68101480-db12-11ea-99b0-fa4271bb8ff2.png)
Although there are no sucessful connections to the Broken site, it says it has 99% availibility.

**Comment by AnandChowdhary** [comment]
This is fixed!

**Comment by AnandChowdhary** [comment]
This is now fixed. 😄
