### ISSUE TITLE
Can't Deploy to GH Pages

### ISSUE THREAD

**Issue by soehlert** [koj-co/upptime#20]
fatal: could not read Username for 'https://github.com': No such device or address

On the "Github Pages Deploy" stage I get the previous error. Do I need to configure some sort of deploy token? I see in the workflows file a `GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}` variable, but the readme for this repo makes me think that should be automatically set?

**Comment by AnandChowdhary** [comment]
The default `GH_TOKEN` does not work with GitHub Pages deploys, please set a secret `GH_PAT` with a personal access token: https://github.com/maxheld83/ghpages#secrets

**Comment by AnandChowdhary** [comment]
I've added docs for `GH_PAT`, but let me know if this doesn't fix your issue?
